{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "educational-chatbot.fullname" . }}
  labels:
    {{- include "educational-chatbot.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "educational-chatbot.backend.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.monitoring.serviceMonitor.path | default "/metrics" }}
    interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
    scrapeTimeout: 10s
    honorLabels: true
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
